[package]
name = "ark-beads"
version = "0.1.1"
description = "Offline automation tool for the Arknights bead minigame"
authors = ["DuRuofu"]
edition = "2024"

[lib]
name = "ark_beads_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
enigo = { version = "0.6.1", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
